# Add project specific ProGuard rules here.
# By default, the flags in this file are appended to flags specified
# in V:\Avinash\CarMindProject\StudioProjects\VoiceJournal/app/proguard-android-optimize.txt

# Missing classes rules generated by R8
-dontwarn com.google.auto.value.AutoValue$Builder
-dontwarn com.google.auto.value.AutoValue

# MediaPipe GenAI ProGuard Rules
# See: https://developers.google.com/mediapipe/solutions/genai/llm_inference/android#proguard_rules
-keep class com.google.mediapipe.tasks.genai.llminference.** { *; }
-keep class com.google.mediapipe.tasks.core.** { *; }
-dontwarn com.google.mediapipe.framework.image.**
